PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE android_metadata (locale TEXT);
INSERT INTO android_metadata VALUES('en_US');
CREATE TABLE `User` (`userId` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `login` TEXT NOT NULL, `password` TEXT NOT NULL);
INSERT INTO User VALUES(1,'abc','abc');
CREATE TABLE `Test` (`testId` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `name` TEXT NOT NULL);
CREATE TABLE `Question` (`questionId` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `text` TEXT NOT NULL, `isRadio` INTEGER NOT NULL);
CREATE TABLE `QuestionOption` (`questionOptionId` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `questionId` INTEGER NOT NULL, `text` TEXT NOT NULL);
CREATE TABLE `QuestionAnswer` (`questionAnswerId` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `index` INTEGER NOT NULL);
CREATE TABLE `UserTestCrossRef` (`userId` INTEGER NOT NULL, `testId` INTEGER NOT NULL, PRIMARY KEY(`userId`, `testId`));
CREATE TABLE `TestQuestionCrossRef` (`testId` INTEGER NOT NULL, `questionId` INTEGER NOT NULL, PRIMARY KEY(`testId`, `questionId`));
CREATE TABLE room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
INSERT INTO room_master_table VALUES(42,'9b7d7ed64645ed24ce06c3e9c18c1645');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('User',1);
CREATE UNIQUE INDEX `index_User_login` ON `User` (`login`);
CREATE UNIQUE INDEX `index_Test_name` ON `Test` (`name`);
CREATE UNIQUE INDEX `index_Question_text` ON `Question` (`text`);
COMMIT;